services:
  - type: web
    name: autoSolo
    env: python
    build:
      pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
