services:
  - type: web
    name: autoSolo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PATH=$PATH:/opt/render/.local/bin gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: POETRY_ENABLED
        value: "false"
